### ISSUE TITLE
Additional information needed when using SIngularity E4S image regarding setting up MODULEPATH

### ISSUE THREAD

**Issue by alansill** [E4S-Project/E4S-Project.github.io#12]
When executing the e4S image as a user on a cluster node that already has LMod modules defined, I encounter the following problems:

`wget http://tau.uoregon.edu/ecp.simg`
`singularity exec ./ecp.simg /bin/bash --rcfile /etc/bashrc`

produces

Lmod Warning:  The environment MODULEPATH has been changed in unexpected ways.
Lmod is unable to use given MODULEPATH. It is using:

" ... (my usual MODULEPATH, omitted here) ...".

Please use "module use ..." to change MODULEPATH instead. 

/usr/bin/lua: /usr/share/lmod/lmod/libexec/MT.lua:1333: table index is nil
[...]

What steps are needed eithere to avoid passing in the existing MODULEPATH and LMod setup, or to use them (whichever is preferred to work with the E4S image)?

**Comment by alansill** [comment]
Answering my own question, the following seems to work:

`singularity exec --cleanenv ./ecp.simg /bin/bash --rcfile /etc/bashrc`

Please confirm if this is the preferred solution.

**Comment by sameershende** [comment]
Yes, this will work and is the preferred solution. We also use:
singularity run -e ./ecp.simg
