### ISSUE TITLE
add link to Github in home page 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/E4S-Project.github.io#3]
Please consider adding E4S Github org in home page or in Download section in https://e4s-project.github.io/index.html it should be visible on the top somewhere.

There seems to be two orgs. https://github.com/UO-OACISS/e4s and https://github.com/E4S-Project

This is confusing to end-users why there are two orgs, please consider merging these two into one place to avoid confusion. 

I see a link https://github.com/E4S-Project/E4S-Project.github.io/blob/master/download.html#L104 to this repo in the download.html. It would help to put this on top somewhere.

**Comment by eugeneswalker** [comment]
Thank you for pointing this out. We have updated the GitHub links under the Downloads section so that they point to the current location. We are in the process of consolidating under the E4S-Project repo right now, and will update the Download links accordingly when completed.
