### ISSUE TITLE
upload singularity e4s images to Sylabs Cloud 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/E4S-Project.github.io#5]
In the downloads page the simg files can be pushed to sylabs cloud. 

http://tau.uoregon.edu/ecp.simg
http://oaciss.uoregon.edu/e4s/images/e4s_ubuntu1804_gpu_ppc64le_1.1.simg

Just create an account and follow instructions https://sylabs.io/guides/3.5/user-guide/cloud_library.html#pushing-a-container

**Comment by eugeneswalker** [comment]
We will likely upload our next batch of Singularity images to SyLabs cloud or other easily accessible image registry!
